### ISSUE TITLE
No passwd entry for user 'curl'

### ISSUE THREAD

**Issue by Jafterdark** [dale3h/hassio-installer#12]
sudo su curl -sL https://raw.githubusercontent.com/dale3h/hassio-installer/master/hassio_rpi3bp | bash -s
No passwd entry for user 'curl'

now what i don't now how to fix's this
any help is appreciated

**Comment by marduv** [comment]
@Jafterdark You need to split up the commands.
`sudo su`
`curl -sL https://raw.githubusercontent.com/dale3h/hassio-installer/master/hassio_rpi3bp | bash -s`

The second argument on `su`is a username, that's why you get `No passwd entry for user 'curl'`.
If it is left blank it will login as root user, and that is what you like to do in this case.

**Comment by Jafterdark** [comment]
now im getting this

root@hassbian:/home/pi# curl -sL https://raw.githubusercontent.com/dale3h/hassio-installer/master/hassio_rpi3bp | bash -s
main: line 40: /etc/hostname: Permission denied
sed: -e expression #1, char 8: unknown option to `s'

**Comment by marduv** [comment]
@Jafterdark as i mentioned
> **Note:**
There is currently an known issue with the setup se issue: #9

If you take a look at that issue you will find the solution ;-)

**Comment by dale3h** [comment]
Closed via #10
